load "field_now.m";
seq:=[];
load "part_table_folder/table-part-1.m";
seq:=seq cat part_precomputed_table;
load "part_table_folder/table-part-2.m";
seq:=seq cat part_precomputed_table;
load "part_table_folder/table-part-3.m";
seq:=seq cat part_precomputed_table;
load "part_table_folder/table-part-4.m";
seq:=seq cat part_precomputed_table;
load "part_table_folder/table-part-5.m";
seq:=seq cat part_precomputed_table;
load "part_table_folder/table-part-6.m";
seq:=seq cat part_precomputed_table;
load "part_table_folder/table-part-7.m";
seq:=seq cat part_precomputed_table;
load "part_table_folder/table-part-8.m";
seq:=seq cat part_precomputed_table;
load "part_table_folder/table-part-9.m";
seq:=seq cat part_precomputed_table;
load "part_table_folder/table-part-10.m";
seq:=seq cat part_precomputed_table;
load "part_table_folder/table-part-11.m";
seq:=seq cat part_precomputed_table;
load "part_table_folder/table-part-12.m";
seq:=seq cat part_precomputed_table;
load "part_table_folder/table-part-13.m";
seq:=seq cat part_precomputed_table;
load "part_table_folder/table-part-14.m";
seq:=seq cat part_precomputed_table;
load "part_table_folder/table-part-15.m";
seq:=seq cat part_precomputed_table;
load "part_table_folder/table-part-16.m";
seq:=seq cat part_precomputed_table;
load "part_table_folder/table-part-17.m";
seq:=seq cat part_precomputed_table;
load "part_table_folder/table-part-18.m";
seq:=seq cat part_precomputed_table;
load "part_table_folder/table-part-19.m";
seq:=seq cat part_precomputed_table;
load "part_table_folder/table-part-20.m";
seq:=seq cat part_precomputed_table;
load "part_table_folder/table-part-21.m";
seq:=seq cat part_precomputed_table;
load "part_table_folder/table-part-22.m";
seq:=seq cat part_precomputed_table;
load "part_table_folder/table-part-23.m";
seq:=seq cat part_precomputed_table;
load "part_table_folder/table-part-24.m";
seq:=seq cat part_precomputed_table;
load "part_table_folder/table-part-25.m";
seq:=seq cat part_precomputed_table;
cart:=car<Parent(seq[1][1]),Parent(seq[1][2])>;	
tt:={@[cart!<seq[i][1],seq[i][2]>] : i in [1..#seq]@};
seq:=SetToSequence(tt);
delete tt;
printf "\n distinct terms of seq=%o",#seq;
precomputed_table:=seq;
printf "\n #precomputed_table=%o",#precomputed_table;	
PrintFile("table_precomputed.m","precomputed_table:=":Overwrite:=true);
PrintFile("table_precomputed.m",precomputed_table);
PrintFile("table_precomputed.m",";");
