load "field_now.m";
tmp_relation_alg_integer_seq:=[];
tmp_relation_prime_ideal_seq_of_seq:=[];
tmp_relation_exponents_integer_seq_of_seq:=[];
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-1.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-1.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-1.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-2.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-2.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-2.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-3.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-3.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-3.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-4.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-4.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-4.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-5.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-5.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-5.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-6.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-6.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-6.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-7.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-7.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-7.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-8.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-8.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-8.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-9.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-9.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-9.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-10.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-10.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-10.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-11.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-11.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-11.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-12.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-12.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-12.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-13.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-13.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-13.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-14.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-14.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-14.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-15.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-15.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-15.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-16.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-16.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-16.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-17.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-17.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-17.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-18.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-18.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-18.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-19.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-19.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-19.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-20.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-20.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-20.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-21.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-21.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-21.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-22.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-22.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-22.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-23.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-23.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-23.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-24.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-24.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-24.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
load "part_gelin_relation_folder/file_gelin_relation_alg_integer_seq-thread-25.m";
load "part_gelin_relation_folder/file_gelin_relation_prime_ideal_seq_of_seq-thread-25.m";
load "part_gelin_relation_folder/file_gelin_relation_exponents_integer_seq_of_seq-thread-25.m";
tmp_relation_alg_integer_seq:=tmp_relation_alg_integer_seq cat relation_alg_integer_seq;
tmp_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq cat relation_prime_ideal_seq_of_seq;
tmp_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq cat relation_exponents_integer_seq_of_seq;
delete relation_alg_integer_seq;
	       delete relation_prime_ideal_seq_of_seq;
		delete relation_exponents_integer_seq_of_seq;
gelin_relation_alg_integer_seq:=tmp_relation_alg_integer_seq;
gelin_relation_prime_ideal_seq_of_seq:=tmp_relation_prime_ideal_seq_of_seq;
gelin_relation_exponents_integer_seq_of_seq:=tmp_relation_exponents_integer_seq_of_seq;
gelin_relation_seq:=[];
printf "\ntotal number of relations collected=%o",#gelin_relation_alg_integer_seq;
for i in [1..#gelin_relation_alg_integer_seq] do
	i1:=ideal<ok|gelin_relation_alg_integer_seq[i]>;
	//i2:=&*[ideal<ok|gelin_relation_prime_ideal_seq_of_seq[i][j]>^gelin_relation_exponents_integer_seq_of_seq[i][j] : j in [1..#gelin_relation_exponents_integer_seq_of_seq[i]]];
	Append(~gelin_relation_seq,i1);
	/*if(i1 ne i2) then
		printf "\n relation %o not valid",i;break;
	elif( i eq #gelin_relation_alg_integer_seq) then
		printf "ALL RELATIONS VALID";
		if(#SequenceToSet(gelin_relation_seq) eq #gelin_relation_seq) then
			printf "\n relations are distinct";
			PrintFile("details.txt","relations are distinct");
		else
			printf "\nrelations are NOT distinct";
			PrintFile("details.txt","relations are NOT distinct");
			printf "\n total number of relations=%o",#gelin_relation_seq;
			printf "\n number of distinct relations=%o",#SequenceToSet(gelin_relation_seq);
			printf "\n in terms of exponents distinct EXPONENTS=%o",#SequenceToSet(gelin_relation_exponents_integer_seq_of_seq);
		end if;
	end if;*/
end for;


if(#SequenceToSet(gelin_relation_seq) eq #gelin_relation_seq) then
			printf "\n relations are distinct";
			PrintFile("details.txt","relations are distinct");
		else
			printf "\nrelations are NOT distinct";
			PrintFile("details.txt","relations are NOT distinct");
			printf "\n total number of relations=%o",#gelin_relation_seq;
			printf "\n number of distinct relations=%o",#SequenceToSet(gelin_relation_seq);
			printf "\n in terms of exponents distinct EXPONENTS=%o",#SequenceToSet(gelin_relation_exponents_integer_seq_of_seq);
		end if;
PrintFile("details.txt","total number of relations=");
PrintFile("details.txt",#gelin_relation_seq);
PrintFile("details.txt","number of distinct relations=");
PrintFile("details.txt",#SequenceToSet(gelin_relation_seq));

